{% set name = "perl-uri-query" %}
{% set version = "0.16" %}
{% set sha256 = "b4e62de79b468dcd7ee835e4dfd0035c83faf92e6c44b79bcdd9a50287fb8c18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/G/GA/GAVINC/URI-Query-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-clone
    - perl-uri
  run:
    - perl

test:
  imports:
    - URI::Query

about:
  home: https://github.com/gavincarr/URI-Query
  summary: 'class providing URI query string manipulation'
  description: |
    URI::Query provides simple URI query string manipulation, allowing you to create and manipulate URI query strings from GET and POST requests in web applications. This is primarily useful for creating links where you wish to preserve some subset of the parameters to the current request, and potentially add or replace others. Given a query string this is doable with regexes, of course, but making sure you get the anchoring and escaping right is tedious and error-prone - this module is simpler.
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  dev_url: https://github.com/gavincarr/URI-Query

extra:
  recipe-maintainers:
    - fgiacomoni
    - conda-forge/perl-packagers
